import fs from "node:fs";
import path from "node:path";
import type { AppConfig } from "../config/types.js";
import { FirestoreRestClient } from "../firestore/firestoreRestClient.js";
import type { FirestoreDocumentLike } from "../firestore/types.js";
import type { Logger } from "../util/logger.js";
import { captureDocument, type CapturedDocument } from "./capturedValue.js";
import {
  cleanupTransientWorkspaces,
  commitCapture,
  ensureGitRepository,
  promoteWorkspace,
  recoverInterruptedWorkspace,
  resetStagingDirectory,
  stageCapture,
  writeJson,
  writeText
} from "./captureWorkspace.js";

export { captureValue } from "./capturedValue.js";

export const defaultCaptureOutputDir = "./data/kin-source-control";
const identityFields = [
  "ai_name",
  "ai_gender",
  "ai_backstory",
  "ai_memory",
  "ai_example_message",
  "ai_directive",
  "ai_additional_context",
  "current_scene",
  "voice_call_directive",
  "voice_call_unified_context",
  "proactive_action_directive",
  "custom_avatar_description",
  "custom_avatar_face_prompt",
  "background_settings",
  "journal_keyphrases",
  "time_awareness",
  "reasoning_effort",
  "llm_flair",
  "user_set_temperature",
  "disable_ltm_recall",
  "disable_ltm_consolidate"
] as const;

const groupIdentityFields = [
  "group_name",
  "group_context",
  "group_directive",
  "current_scene",
  "current_scene_suggestion",
  "group_ais",
  "share_short_term_memory",
  "use_manual_turntaking",
  "disable_ltm_recall",
  "disable_ltm_consolidate"
] as const;

export interface CaptureKindroidStateOptions {
  outputDir?: string;
  commit?: boolean;
  message?: string;
}

export interface CaptureKindroidStateResult {
  outputDir: string;
  committed: boolean;
  createdCommit: boolean;
  commitHash?: string;
  kinCount: number;
  groupCount: number;
  kinJournalEntryCount: number;
  globalJournalEntryCount: number;
}

export async function captureKindroidState(
  config: AppConfig,
  logger: Logger,
  options: CaptureKindroidStateOptions = {}
): Promise<CaptureKindroidStateResult> {
  const outputDir = path.resolve(process.cwd(), options.outputDir ?? defaultCaptureOutputDir);
  const workspaceDir = path.join(outputDir, "workspace");
  const stagingDir = path.join(outputDir, `.workspace-next-${process.pid}-${Date.now()}`);
  const rest = new FirestoreRestClient(config, logger);
  const uid = await rest.resolveUid();

  fs.mkdirSync(outputDir, { recursive: true });
  await ensureGitRepository(outputDir);
  recoverInterruptedWorkspace(outputDir, workspaceDir);
  cleanupTransientWorkspaces(outputDir);
  resetStagingDirectory(stagingDir, outputDir);

  try {
    const kins = await rest.listDocuments({
      collectionPath: `Users/${uid}/AIs`,
      pageSize: 100,
      logLabel: "capture.kins"
    });
    const groups = await rest.listDocuments({
      collectionPath: `Users/${uid}/Groups`,
      pageSize: 100,
      logLabel: "capture.groups"
    });
    const globalJournalEntries = await rest.listDocuments({
      collectionPath: `Users/${uid}/GlobalJournalV3`,
      pageSize: 100,
      maxDocuments: 500,
      orderBy: "created desc",
      logLabel: "capture.globalJournal"
    });

    const capturedAt = new Date().toISOString();
    const manifest = {
      schemaVersion: 1,
      firebaseProjectId: config.kindroid.firebaseProjectId,
      kinCount: kins.length,
      groupCount: groups.length,
      paths: {
        kins: "kins",
        groups: "groups",
        globalJournal: "global-journal"
      },
      notes: [
        "This repository is generated by kinagent capture-state.",
        "It is local private state and should not be committed to the kinagent application repository.",
        "Text fields are decrypted where the saved Firebase UID can decrypt them; otherwise raw values are preserved in JSON metadata."
      ]
    };
    writeJson(path.join(stagingDir, "manifest.json"), manifest);
    writeText(path.join(stagingDir, "README.md"), captureReadme());

    let kinJournalEntryCount = 0;
    for (const kin of kins) {
      const kinDir = path.join(stagingDir, "kins", resourceFolderName(kin));
      const captured = captureDocument(kin, uid, identityFields);
      writeCapturedDocument(kinDir, captured);

      const journalEntries = await rest.listDocuments({
        collectionPath: `Users/${uid}/AIs/${kin.id}/JournalV3`,
        pageSize: 100,
        maxDocuments: 500,
        orderBy: "created desc",
        logLabel: "capture.kinJournal"
      });
      kinJournalEntryCount += journalEntries.length;
      writeJournalEntries(path.join(kinDir, "journal"), journalEntries, uid);
    }

    for (const group of groups) {
      const groupDir = path.join(stagingDir, "groups", resourceFolderName(group));
      writeCapturedDocument(groupDir, captureDocument(group, uid, groupIdentityFields));
    }

    writeJournalEntries(path.join(stagingDir, "global-journal"), globalJournalEntries, uid);
    promoteWorkspace(stagingDir, workspaceDir, outputDir);

    await stageCapture(outputDir);
    const committed = options.commit ?? true;
    const commitResult = committed
      ? await commitCapture(outputDir, options.message ?? `Capture Kindroid identity state ${capturedAt}`)
      : { commitHash: undefined, createdCommit: false };

    return {
      outputDir,
      committed,
      createdCommit: commitResult.createdCommit,
      commitHash: commitResult.commitHash,
      kinCount: kins.length,
      groupCount: groups.length,
      kinJournalEntryCount,
      globalJournalEntryCount: globalJournalEntries.length
    };
  } finally {
    fs.rmSync(stagingDir, { recursive: true, force: true });
  }
}

function writeCapturedDocument(dir: string, document: CapturedDocument): void {
  writeJson(path.join(dir, "profile.json"), document);
  const fieldsDir = path.join(dir, "fields");
  for (const [field, value] of Object.entries(document.fields)) {
    if (value.kind === "string" && typeof value.value === "string") {
      writeText(path.join(fieldsDir, `${safeFileName(field)}.md`), `${value.value.trim()}\n`);
      continue;
    }

    writeJson(path.join(fieldsDir, `${safeFileName(field)}.json`), value.value ?? value);
  }
}

function writeJournalEntries(dir: string, documents: FirestoreDocumentLike[], decryptionKey: string): void {
  if (documents.length === 0) {
    writeJson(path.join(dir, "entries.json"), []);
    return;
  }

  const entries = documents.map((document) =>
    captureDocument(document, decryptionKey, ["id", "entry", "keyphrases", "created", "is_global"])
  );
  writeJson(path.join(dir, "entries.json"), entries);

  for (const entry of entries) {
    const entryText = entry.fields.entry;
    if (entryText?.kind === "string" && typeof entryText.value === "string") {
      const keyphrases = entry.fields.keyphrases?.value;
      const keyphraseLines = Array.isArray(keyphrases) ? keyphrases.map((item) => `- ${String(item)}`).join("\n") : "";
      writeText(
        path.join(dir, `${safeFileName(entry.id)}.md`),
        [`# ${entry.id}`, "", entryText.value.trim(), "", "## Keyphrases", keyphraseLines || "(none)", ""].join("\n")
      );
    }
  }
}

function resourceFolderName(document: FirestoreDocumentLike): string {
  const data = document.data();
  const record = typeof data === "object" && data !== null ? (data as Record<string, unknown>) : {};
  const name = stringValue(record.ai_name) ?? stringValue(record.group_name) ?? document.id;
  return `${safeFileName(name)}--${safeFileName(document.id)}`;
}

function stringValue(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}

function safeFileName(value: string): string {
  const normalized = value
    .normalize("NFKD")
    .replace(/[^\w.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return normalized || "unnamed";
}

function captureReadme(): string {
  return [
    "# Kindroid Identity State",
    "",
    "This repository is generated by kinagent. It is intended for local review, diffs, and rollback planning.",
    "",
    "- `profile.json` preserves exact field mapping and decryption metadata.",
    "- `fields/*.md` contains readable text where available.",
    "- `journal/entries.json` and journal markdown files capture Kin journal entries.",
    ""
  ].join("\n");
}
