import { execFile } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import type { AppConfig } from "../config/types.js";
import { FirestoreRestClient } from "../firestore/firestoreRestClient.js";
import type { FirestoreDocumentLike } from "../firestore/types.js";
import { decryptKindroidValue } from "../kindroid/kindroidCrypto.js";
import type { Logger } from "../util/logger.js";

const execFileAsync = promisify(execFile);

export const defaultCaptureOutputDir = "./data/kin-source-control";
const identityFields = [
  "ai_name",
  "ai_gender",
  "ai_backstory",
  "ai_memory",
  "ai_example_message",
  "ai_directive",
  "ai_additional_context",
  "current_scene",
  "voice_call_directive",
  "voice_call_unified_context",
  "proactive_action_directive",
  "custom_avatar_description",
  "custom_avatar_face_prompt",
  "background_settings",
  "journal_keyphrases",
  "time_awareness",
  "reasoning_effort",
  "llm_flair",
  "user_set_temperature",
  "disable_ltm_recall",
  "disable_ltm_consolidate"
] as const;

const groupIdentityFields = [
  "group_name",
  "group_context",
  "group_directive",
  "current_scene",
  "current_scene_suggestion",
  "group_ais",
  "share_short_term_memory",
  "use_manual_turntaking",
  "disable_ltm_recall",
  "disable_ltm_consolidate"
] as const;

export interface CaptureKindroidStateOptions {
  outputDir?: string;
  commit?: boolean;
  message?: string;
}

export interface CaptureKindroidStateResult {
  outputDir: string;
  committed: boolean;
  createdCommit: boolean;
  commitHash?: string;
  kinCount: number;
  groupCount: number;
  kinJournalEntryCount: number;
  globalJournalEntryCount: number;
}

interface CapturedField {
  kind: "string" | "number" | "boolean" | "array" | "object" | "null" | "unknown";
  encrypted?: boolean;
  decrypted?: boolean;
  rawLength?: number;
  valueLength?: number;
  value?: unknown;
  keys?: string[];
  count?: number;
}

interface CapturedDocument {
  id: string;
  createTime?: string;
  updateTime?: string;
  fields: Record<string, CapturedField>;
}

interface CapturedNestedValue {
  value: unknown;
  encrypted: boolean;
  decrypted: boolean;
}

export async function captureKindroidState(
  config: AppConfig,
  logger: Logger,
  options: CaptureKindroidStateOptions = {}
): Promise<CaptureKindroidStateResult> {
  const outputDir = path.resolve(process.cwd(), options.outputDir ?? defaultCaptureOutputDir);
  const workspaceDir = path.join(outputDir, "workspace");
  const stagingDir = path.join(outputDir, `.workspace-next-${process.pid}-${Date.now()}`);
  const rest = new FirestoreRestClient(config, logger);
  const uid = await rest.resolveUid();

  fs.mkdirSync(outputDir, { recursive: true });
  await ensureGitRepository(outputDir);
  recoverInterruptedWorkspace(outputDir, workspaceDir);
  cleanupTransientWorkspaces(outputDir);
  resetStagingDirectory(stagingDir, outputDir);

  try {
    const kins = await rest.listDocuments({
      collectionPath: `Users/${uid}/AIs`,
      pageSize: 100,
      logLabel: "capture.kins"
    });
    const groups = await rest.listDocuments({
      collectionPath: `Users/${uid}/Groups`,
      pageSize: 100,
      logLabel: "capture.groups"
    });
    const globalJournalEntries = await rest.listDocuments({
      collectionPath: `Users/${uid}/GlobalJournalV3`,
      pageSize: 100,
      maxDocuments: 500,
      orderBy: "created desc",
      logLabel: "capture.globalJournal"
    });

    const capturedAt = new Date().toISOString();
    const manifest = {
      schemaVersion: 1,
      firebaseProjectId: config.kindroid.firebaseProjectId,
      kinCount: kins.length,
      groupCount: groups.length,
      paths: {
        kins: "kins",
        groups: "groups",
        globalJournal: "global-journal"
      },
      notes: [
        "This repository is generated by kinagent capture-state.",
        "It is local private state and should not be committed to the kinagent application repository.",
        "Text fields are decrypted where the saved Firebase UID can decrypt them; otherwise raw values are preserved in JSON metadata."
      ]
    };
    writeJson(path.join(stagingDir, "manifest.json"), manifest);
    writeText(path.join(stagingDir, "README.md"), captureReadme());

    let kinJournalEntryCount = 0;
    for (const kin of kins) {
      const kinDir = path.join(stagingDir, "kins", resourceFolderName(kin));
      const captured = captureDocument(kin, uid, identityFields);
      writeCapturedDocument(kinDir, captured);

      const journalEntries = await rest.listDocuments({
        collectionPath: `Users/${uid}/AIs/${kin.id}/JournalV3`,
        pageSize: 100,
        maxDocuments: 500,
        orderBy: "created desc",
        logLabel: "capture.kinJournal"
      });
      kinJournalEntryCount += journalEntries.length;
      writeJournalEntries(path.join(kinDir, "journal"), journalEntries, uid);
    }

    for (const group of groups) {
      const groupDir = path.join(stagingDir, "groups", resourceFolderName(group));
      writeCapturedDocument(groupDir, captureDocument(group, uid, groupIdentityFields));
    }

    writeJournalEntries(path.join(stagingDir, "global-journal"), globalJournalEntries, uid);
    promoteWorkspace(stagingDir, workspaceDir, outputDir);

    await stageCapture(outputDir);
    const committed = options.commit ?? true;
    const commitResult = committed
      ? await commitCapture(outputDir, options.message ?? `Capture Kindroid identity state ${capturedAt}`)
      : { commitHash: undefined, createdCommit: false };

    return {
      outputDir,
      committed,
      createdCommit: commitResult.createdCommit,
      commitHash: commitResult.commitHash,
      kinCount: kins.length,
      groupCount: groups.length,
      kinJournalEntryCount,
      globalJournalEntryCount: globalJournalEntries.length
    };
  } finally {
    fs.rmSync(stagingDir, { recursive: true, force: true });
  }
}

function captureDocument(
  document: FirestoreDocumentLike,
  decryptionKey: string,
  fields: readonly string[]
): CapturedDocument {
  const data = document.data();
  const record = typeof data === "object" && data !== null ? (data as Record<string, unknown>) : {};
  const capturedFields = Object.fromEntries(
    fields.filter((field) => field in record).map((field) => [field, captureValue(record[field], decryptionKey)])
  );

  return {
    id: document.id,
    createTime: typeof record._createTime === "string" ? record._createTime : undefined,
    updateTime: typeof record._updateTime === "string" ? record._updateTime : undefined,
    fields: capturedFields
  };
}

export function captureValue(value: unknown, decryptionKey: string): CapturedField {
  if (typeof value === "string") {
    const decrypted = decryptKindroidValue(value, decryptionKey);
    return {
      kind: "string",
      encrypted: decrypted.encrypted,
      decrypted: decrypted.decrypted,
      rawLength: value.length,
      valueLength: decrypted.value.length,
      value: decrypted.value
    };
  }

  if (typeof value === "number") {
    return { kind: "number", value };
  }

  if (typeof value === "boolean") {
    return { kind: "boolean", value };
  }

  if (value === null) {
    return { kind: "null", value: null };
  }

  if (Array.isArray(value)) {
    const captured = captureNestedValue(value, decryptionKey);
    return {
      kind: "array",
      count: value.length,
      encrypted: captured.encrypted || undefined,
      decrypted: captured.decrypted || undefined,
      value: captured.value
    };
  }

  if (typeof value === "object" && value !== null) {
    const captured = captureNestedValue(value, decryptionKey);
    return {
      kind: "object",
      keys: Object.keys(value).sort(),
      encrypted: captured.encrypted || undefined,
      decrypted: captured.decrypted || undefined,
      value: captured.value
    };
  }

  return { kind: "unknown" };
}

function captureNestedValue(value: unknown, decryptionKey: string): CapturedNestedValue {
  if (typeof value === "string") {
    const decrypted = decryptKindroidValue(value, decryptionKey);
    return {
      value: decrypted.value,
      encrypted: decrypted.encrypted,
      decrypted: decrypted.decrypted
    };
  }

  if (Array.isArray(value)) {
    const items = value.map((item) => captureNestedValue(item, decryptionKey));
    return {
      value: items.map((item) => item.value),
      encrypted: items.some((item) => item.encrypted),
      decrypted: items.some((item) => item.decrypted)
    };
  }

  if (value && typeof value === "object") {
    const entries = Object.entries(value).map(([key, item]) => [key, captureNestedValue(item, decryptionKey)] as const);
    return {
      value: Object.fromEntries(entries.map(([key, item]) => [key, item.value])),
      encrypted: entries.some(([, item]) => item.encrypted),
      decrypted: entries.some(([, item]) => item.decrypted)
    };
  }

  return {
    value,
    encrypted: false,
    decrypted: false
  };
}

function writeCapturedDocument(dir: string, document: CapturedDocument): void {
  writeJson(path.join(dir, "profile.json"), document);
  const fieldsDir = path.join(dir, "fields");
  for (const [field, value] of Object.entries(document.fields)) {
    if (value.kind === "string" && typeof value.value === "string") {
      writeText(path.join(fieldsDir, `${safeFileName(field)}.md`), `${value.value.trim()}\n`);
      continue;
    }

    writeJson(path.join(fieldsDir, `${safeFileName(field)}.json`), value.value ?? value);
  }
}

function writeJournalEntries(dir: string, documents: FirestoreDocumentLike[], decryptionKey: string): void {
  if (documents.length === 0) {
    writeJson(path.join(dir, "entries.json"), []);
    return;
  }

  const entries = documents.map((document) =>
    captureDocument(document, decryptionKey, ["id", "entry", "keyphrases", "created", "is_global"])
  );
  writeJson(path.join(dir, "entries.json"), entries);

  for (const entry of entries) {
    const entryText = entry.fields.entry;
    if (entryText?.kind === "string" && typeof entryText.value === "string") {
      const keyphrases = entry.fields.keyphrases?.value;
      const keyphraseLines = Array.isArray(keyphrases) ? keyphrases.map((item) => `- ${String(item)}`).join("\n") : "";
      writeText(
        path.join(dir, `${safeFileName(entry.id)}.md`),
        [`# ${entry.id}`, "", entryText.value.trim(), "", "## Keyphrases", keyphraseLines || "(none)", ""].join("\n")
      );
    }
  }
}

function resourceFolderName(document: FirestoreDocumentLike): string {
  const data = document.data();
  const record = typeof data === "object" && data !== null ? (data as Record<string, unknown>) : {};
  const name = stringValue(record.ai_name) ?? stringValue(record.group_name) ?? document.id;
  return `${safeFileName(name)}--${safeFileName(document.id)}`;
}

function stringValue(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}

function safeFileName(value: string): string {
  const normalized = value
    .normalize("NFKD")
    .replace(/[^\w.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return normalized || "unnamed";
}

function resetStagingDirectory(dir: string, outputDir: string): void {
  const resolved = path.resolve(dir);
  const resolvedOutputDir = path.resolve(outputDir);
  if (
    !path.basename(resolved).startsWith(".workspace-next-") ||
    !resolved.startsWith(`${resolvedOutputDir}${path.sep}`)
  ) {
    throw new Error(`Refusing to reset unexpected capture staging directory: ${resolved}`);
  }

  fs.rmSync(resolved, { recursive: true, force: true });
  fs.mkdirSync(resolved, { recursive: true });
}

function promoteWorkspace(stagingDir: string, workspaceDir: string, outputDir: string): void {
  const resolvedOutputDir = path.resolve(outputDir);
  const resolvedStagingDir = path.resolve(stagingDir);
  const resolvedWorkspaceDir = path.resolve(workspaceDir);
  const backupDir = path.join(outputDir, `.workspace-prev-${process.pid}-${Date.now()}`);

  if (
    !path.basename(resolvedStagingDir).startsWith(".workspace-next-") ||
    !resolvedStagingDir.startsWith(`${resolvedOutputDir}${path.sep}`) ||
    path.basename(resolvedWorkspaceDir) !== "workspace" ||
    !resolvedWorkspaceDir.startsWith(`${resolvedOutputDir}${path.sep}`)
  ) {
    throw new Error("Refusing to promote unexpected capture workspace paths.");
  }

  let backupCreated = false;
  try {
    if (fs.existsSync(resolvedWorkspaceDir)) {
      fs.renameSync(resolvedWorkspaceDir, backupDir);
      backupCreated = true;
    }

    fs.renameSync(resolvedStagingDir, resolvedWorkspaceDir);
    if (backupCreated) {
      fs.rmSync(backupDir, { recursive: true, force: true });
    }
  } catch (error) {
    if (backupCreated && !fs.existsSync(resolvedWorkspaceDir) && fs.existsSync(backupDir)) {
      fs.renameSync(backupDir, resolvedWorkspaceDir);
    }

    throw error;
  }
}

function writeJson(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(stableValue(value), null, 2)}\n`, "utf8");
}

function writeText(filePath: string, value: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, value, "utf8");
}

function captureReadme(): string {
  return [
    "# Kindroid Identity State",
    "",
    "This repository is generated by kinagent. It is intended for local review, diffs, and rollback planning.",
    "",
    "- `profile.json` preserves exact field mapping and decryption metadata.",
    "- `fields/*.md` contains readable text where available.",
    "- `journal/entries.json` and journal markdown files capture Kin journal entries.",
    ""
  ].join("\n");
}

async function ensureGitRepository(outputDir: string): Promise<void> {
  if (!fs.existsSync(path.join(outputDir, ".git"))) {
    await execFileAsync("git", ["init"], { cwd: outputDir });
    await execFileAsync("git", ["config", "user.name", "Kinagent Capture"], { cwd: outputDir });
    await execFileAsync("git", ["config", "user.email", "kinagent-capture@local"], { cwd: outputDir });
  }

  ensureCaptureGitExcludes(outputDir);
}

function recoverInterruptedWorkspace(outputDir: string, workspaceDir: string): void {
  if (fs.existsSync(workspaceDir)) {
    return;
  }

  const backups = transientWorkspaceDirs(outputDir, ".workspace-prev-");
  const latestBackup = backups.at(-1);
  if (latestBackup) {
    fs.renameSync(latestBackup, workspaceDir);
  }
}

function cleanupTransientWorkspaces(outputDir: string): void {
  for (const dir of transientWorkspaceDirs(outputDir, ".workspace-next-")) {
    fs.rmSync(dir, { recursive: true, force: true });
  }

  for (const dir of transientWorkspaceDirs(outputDir, ".workspace-prev-")) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function transientWorkspaceDirs(outputDir: string, prefix: string): string[] {
  return fs
    .readdirSync(outputDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith(prefix))
    .map((entry) => path.join(outputDir, entry.name))
    .sort();
}

function ensureCaptureGitExcludes(outputDir: string): void {
  const excludePath = path.join(outputDir, ".git", "info", "exclude");
  const excludeLines = [".workspace-next-*", ".workspace-prev-*"];
  const existing = fs.existsSync(excludePath) ? fs.readFileSync(excludePath, "utf8") : "";
  const missing = excludeLines.filter((line) => !existing.split(/\r?\n/).includes(line));
  if (missing.length > 0) {
    fs.mkdirSync(path.dirname(excludePath), { recursive: true });
    fs.appendFileSync(
      excludePath,
      `${existing.endsWith("\n") || existing.length === 0 ? "" : "\n"}${missing.join("\n")}\n`
    );
  }
}

async function stageCapture(outputDir: string): Promise<void> {
  await execFileAsync("git", ["add", "--", "workspace"], { cwd: outputDir });
}

async function commitCapture(
  outputDir: string,
  message: string
): Promise<{ commitHash?: string; createdCommit: boolean }> {
  const status = await execFileAsync("git", ["status", "--porcelain", "--", "workspace"], { cwd: outputDir });
  if (!status.stdout.trim()) {
    return { commitHash: await currentCommit(outputDir), createdCommit: false };
  }

  await execFileAsync("git", ["commit", "-m", message], { cwd: outputDir });
  return { commitHash: await currentCommit(outputDir), createdCommit: true };
}

async function currentCommit(outputDir: string): Promise<string | undefined> {
  try {
    const result = await execFileAsync("git", ["rev-parse", "--short", "HEAD"], { cwd: outputDir });
    return result.stdout.trim();
  } catch {
    return undefined;
  }
}

function stableValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(stableValue);
  }

  if (!value || typeof value !== "object") {
    return value;
  }

  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, item]) => [key, stableValue(item)])
  );
}
