import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";

type RendererEventCallback = (message: unknown) => void;

const kinagentApi = {
  getStatus: () => ipcRenderer.invoke("app:get-status"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (input: unknown) => ipcRenderer.invoke("settings:save", input),
  pruneProfileData: () => ipcRenderer.invoke("settings:prune-profile-data"),
  clearSavedSession: () => ipcRenderer.invoke("settings:clear-saved-session"),
  clearCache: () => ipcRenderer.invoke("settings:clear-cache"),
  setCaptureVaultEnabled: (input: unknown) => ipcRenderer.invoke("settings:capture-vault-enable", input),
  unlockCaptureVault: () => ipcRenderer.invoke("settings:capture-vault-unlock"),
  openProfileFolder: () => ipcRenderer.invoke("settings:open-profile-folder"),
  getBrowserIntegrationStatus: () => ipcRenderer.invoke("browser-integration:get-status"),
  saveBrowserIntegrationSettings: (input: unknown) => ipcRenderer.invoke("browser-integration:save-settings", input),
  registerBrowserIntegration: (input: unknown) => ipcRenderer.invoke("browser-integration:register", input),
  unregisterBrowserIntegration: () => ipcRenderer.invoke("browser-integration:unregister"),
  testBrowserIntegrationNotice: () => ipcRenderer.invoke("browser-integration:test-notice"),
  testBrowserIntegrationReload: () => ipcRenderer.invoke("browser-integration:test-reload"),
  listTimelineEvents: (input: unknown) => ipcRenderer.invoke("timeline:list", input),
  exportTimelineEvents: (input: unknown) => ipcRenderer.invoke("timeline:export-json", input),
  openKindroid: () => ipcRenderer.invoke("app:open-kindroid"),
  startLogin: () => ipcRenderer.invoke("login:start"),
  saveLogin: () => ipcRenderer.invoke("login:save"),
  cancelLogin: () => ipcRenderer.invoke("login:cancel"),
  startMonitor: (input: unknown) => ipcRenderer.invoke("monitor:start", input),
  stopMonitor: () => ipcRenderer.invoke("monitor:stop"),
  setKinEnabled: (input: unknown) => ipcRenderer.invoke("kins:set-enabled", input),
  refreshKins: () => ipcRenderer.invoke("kins:refresh"),
  setGroupEnabled: (input: unknown) => ipcRenderer.invoke("groups:set-enabled", input),
  refreshGroups: () => ipcRenderer.invoke("groups:refresh"),
  getCapturedKin: (input: unknown) => ipcRenderer.invoke("capture:get-kin", input),
  getCapturedGroup: (input: unknown) => ipcRenderer.invoke("capture:get-group", input),
  listJournalSuggestions: () => ipcRenderer.invoke("journal:list-suggestions"),
  acceptJournalSuggestion: (input: unknown) => ipcRenderer.invoke("journal:accept-suggestion", input),
  deleteInvalidatedJournalSuggestion: (input: unknown) =>
    ipcRenderer.invoke("journal:delete-invalidated-suggestion", input),
  dismissJournalSuggestion: (input: unknown) => ipcRenderer.invoke("journal:dismiss-suggestion", input),
  listGroupBackgroundSuggestions: () => ipcRenderer.invoke("background:list-group-suggestions"),
  dismissGroupBackgroundSuggestion: (input: unknown) =>
    ipcRenderer.invoke("background:dismiss-group-suggestion", input),
  generateGroupBackgroundImage: (input: unknown) => ipcRenderer.invoke("background:generate-group-image", input),
  applyGroupBackgroundImage: (input: unknown) => ipcRenderer.invoke("background:apply-group-image", input),
  getGroupBackgroundPreference: (input: unknown) => ipcRenderer.invoke("background:get-group-preference", input),
  setGroupBackgroundPreference: (input: unknown) => ipcRenderer.invoke("background:set-group-preference", input),
  getKinVoicePreference: (input: unknown) => ipcRenderer.invoke("voice:get-kin-preference", input),
  setKinVoicePreference: (input: unknown) => ipcRenderer.invoke("voice:set-kin-preference", input),
  getGroupSoundscapePreference: (input: unknown) => ipcRenderer.invoke("soundscape:get-group-preference", input),
  setGroupSoundscapePreference: (input: unknown) => ipcRenderer.invoke("soundscape:set-group-preference", input),
  getGroupGamingPreference: (input: unknown) => ipcRenderer.invoke("gaming:get-group-preference", input),
  setGroupGamingPreference: (input: unknown) => ipcRenderer.invoke("gaming:set-group-preference", input),
  approveGroupGamingKeeperSuggestion: (input: unknown) => ipcRenderer.invoke("gaming:approve-keeper-suggestion", input),
  importCampaignPack: () => ipcRenderer.invoke("gaming:import-campaign-pack"),
  forceLocalScenePrewarm: (input: unknown) => ipcRenderer.invoke("prewarm:local-scene", input),
  forceSoundscapePrewarm: (input: unknown) => ipcRenderer.invoke("prewarm:soundscape", input),
  forcePreviouslyOnPrewarm: (input: unknown) => ipcRenderer.invoke("prewarm:previously-on", input),
  forceGroupBackgroundPrewarm: (input: unknown) => ipcRenderer.invoke("prewarm:group-background", input),
  getKinAmbientPreference: (input: unknown) => ipcRenderer.invoke("ambient:get-kin-preference", input),
  setKinAmbientPreference: (input: unknown) => ipcRenderer.invoke("ambient:set-kin-preference", input),
  getScreenContextSettings: () => ipcRenderer.invoke("screen-context:get-settings"),
  saveScreenContextSettings: (input: unknown) => ipcRenderer.invoke("screen-context:save-settings", input),
  setCurrentScreenContextKin: (input: unknown) => ipcRenderer.invoke("screen-context:set-current-kin", input),
  analyzeScreenContext: (input: unknown) => ipcRenderer.invoke("screen-context:analyze", input),
  sendScreenContext: (input: unknown) => ipcRenderer.invoke("screen-context:send", input),
  discardScreenContext: (input: unknown) => ipcRenderer.invoke("screen-context:discard", input),
  exportKinChat: (input: unknown) => ipcRenderer.invoke("chat-export:kin", input),
  exportGroupChat: (input: unknown) => ipcRenderer.invoke("chat-export:group", input),
  generateStorybook: (input: unknown) => ipcRenderer.invoke("storybook:generate", input),
  importStorybookTranscript: (input: unknown) => ipcRenderer.invoke("storybook:import-generate", input),
  saveStorybookPdf: (input: unknown) => ipcRenderer.invoke("storybook:save-pdf", input),
  analyzeKin: (input: unknown) => ipcRenderer.invoke("kin-analyze:run", input),
  readSoundscapeAsset: (input: unknown) => ipcRenderer.invoke("soundscape:read-asset", input),
  onEvent: (callback: RendererEventCallback) => {
    const listener = (_event: IpcRendererEvent, message: unknown) => callback(message);
    ipcRenderer.on("app:event", listener);
    return () => ipcRenderer.removeListener("app:event", listener);
  }
};

contextBridge.exposeInMainWorld("kinagent", kinagentApi);
